export const countries = [
  { name: 'Afganistan', code: 'AF' },
  { name: 'Albania', code: 'AL' },
  { name: 'Algieria', code: 'DZ' },
  { name: 'Andora', code: 'AD' },
  { name: 'Angola', code: 'AO' },
  { name: 'Antigua i Barbuda', code: 'AG' },
  { name: 'Argentyna', code: 'AR' },
  { name: 'Armenia', code: 'AM' },
  { name: 'Australia', code: 'AU' },
  { name: 'Austria', code: 'AT' },
  { name: 'Azerbejdżan', code: 'AZ' },
  { name: 'Bahamy', code: 'BS' },
  { name: 'Bahrajn', code: 'BH' },
  { name: 'Bangladesz', code: 'BD' },
  { name: 'Barbados', code: 'BB' },
  { name: 'Białoruś', code: 'BY' },
  { name: 'Belgia', code: 'BE' },
  { name: 'Belize', code: 'BZ' },
  { name: 'Benin', code: 'BJ' },
  { name: 'Bhutan', code: 'BT' },
  { name: 'Boliwia', code: 'BO' },
  { name: 'Bośnia i Hercegowina', code: 'BA' },
  { name: 'Botswana', code: 'BW' },
  { name: 'Brazylia', code: 'BR' },
  { name: 'Brunei', code: 'BN' },
  { name: 'Bułgaria', code: 'BG' },
  { name: 'Burkina Faso', code: 'BF' },
  { name: 'Burundi', code: 'BI' },
  { name: 'Cabo Verde', code: 'CV' },
  { name: 'Kambodża', code: 'KH' },
  { name: 'Kamerun', code: 'CM' },
  { name: 'Kanada', code: 'CA' },
  { name: 'Republika Środkowoafrykańska', code: 'CF' },
  { name: 'Czad', code: 'TD' },
  { name: 'Chile', code: 'CL' },
  { name: 'Chiny', code: 'CN' },
  { name: 'Kolumbia', code: 'CO' },
  { name: 'Komory', code: 'KM' },
  { name: 'Kongo (Kongo-Brazzaville)', code: 'CG' },
  { name: 'Kostaryka', code: 'CR' },
  { name: 'Chorwacja', code: 'HR' },
  { name: 'Kuba', code: 'CU' },
  { name: 'Cypr', code: 'CY' },
  { name: 'Czechy', code: 'CZ' },
  { name: 'Demokratyczna Republika Konga', code: 'CD' },
  { name: 'Dania', code: 'DK' },
  { name: 'Dżibuti', code: 'DJ' },
  { name: 'Dominika', code: 'DM' },
  { name: 'Dominikana', code: 'DO' },
  { name: 'Ekwador', code: 'EC' },
  { name: 'Egipt', code: 'EG' },
  { name: 'Salwador', code: 'SV' },
  { name: 'Gwinea Równikowa', code: 'GQ' },
  { name: 'Erytrea', code: 'ER' },
  { name: 'Estonia', code: 'EE' },
  { name: 'Eswatini', code: 'SZ' },
  { name: 'Etiopia', code: 'ET' },
  { name: 'Fidżi', code: 'FJ' },
  { name: 'Finlandia', code: 'FI' },
  { name: 'Francja', code: 'FR' },
  { name: 'Gabon', code: 'GA' },
  { name: 'Gambia', code: 'GM' },
  { name: 'Gruzja', code: 'GE' },
  { name: 'Niemcy', code: 'DE' },
  { name: 'Ghana', code: 'GH' },
  { name: 'Grecja', code: 'GR' },
  { name: 'Grenada', code: 'GD' },
  { name: 'Gwatemala', code: 'GT' },
  { name: 'Gwinea', code: 'GN' },
  { name: 'Gwinea-Bissau', code: 'GW' },
  { name: 'Gujana', code: 'GY' },
  { name: 'Haiti', code: 'HT' },
  { name: 'Honduras', code: 'HN' },
  { name: 'Węgry', code: 'HU' },
  { name: 'Islandia', code: 'IS' },
  { name: 'Indie', code: 'IN' },
  { name: 'Indonezja', code: 'ID' },
  { name: 'Iran', code: 'IR' },
  { name: 'Irak', code: 'IQ' },
  { name: 'Irlandia', code: 'IE' },
  { name: 'Izrael', code: 'IL' },
  { name: 'Włochy', code: 'IT' },
  { name: 'Jamajka', code: 'JM' },
  { name: 'Japonia', code: 'JP' },
  { name: 'Jordania', code: 'JO' },
  { name: 'Kazachstan', code: 'KZ' },
  { name: 'Kenia', code: 'KE' },
  { name: 'Kiribati', code: 'KI' },
  { name: 'Kuwejt', code: 'KW' },
  { name: 'Kirgistan', code: 'KG' },
  { name: 'Laos', code: 'LA' },
  { name: 'Łotwa', code: 'LV' },
  { name: 'Liban', code: 'LB' },
  { name: 'Lesotho', code: 'LS' },
  { name: 'Liberia', code: 'LR' },
  { name: 'Libia', code: 'LY' },
  { name: 'Liechtenstein', code: 'LI' },
  { name: 'Litwa', code: 'LT' },
  { name: 'Luksemburg', code: 'LU' },
  { name: 'Madagaskar', code: 'MG' },
  { name: 'Malawi', code: 'MW' },
  { name: 'Malezja', code: 'MY' },
  { name: 'Malediwy', code: 'MV' },
  { name: 'Mali', code: 'ML' },
  { name: 'Malta', code: 'MT' },
  { name: 'Wyspy Marshalla', code: 'MH' },
  { name: 'Mauretania', code: 'MR' },
  { name: 'Mauritius', code: 'MU' },
  { name: 'Meksyk', code: 'MX' },
  { name: 'Mikronezja', code: 'FM' },
  { name: 'Mołdawia', code: 'MD' },
  { name: 'Monako', code: 'MC' },
  { name: 'Mongolia', code: 'MN' },
  { name: 'Czarnogóra', code: 'ME' },
  { name: 'Maroko', code: 'MA' },
  { name: 'Mozambik', code: 'MZ' },
  { name: 'Mjanma (Birma)', code: 'MM' },
  { name: 'Namibia', code: 'NA' },
  { name: 'Nauru', code: 'NR' },
  { name: 'Nepal', code: 'NP' },
  { name: 'Holandia', code: 'NL' },
  { name: 'Nowa Zelandia', code: 'NZ' },
  { name: 'Nikaragua', code: 'NI' },
  { name: 'Niger', code: 'NE' },
  { name: 'Nigeria', code: 'NG' },
  { name: 'Korea Północna', code: 'KP' },
  { name: 'Macedonia Północna', code: 'MK' },
  { name: 'Norwegia', code: 'NO' },
  { name: 'Oman', code: 'OM' },
  { name: 'Pakistan', code: 'PK' },
  { name: 'Palau', code: 'PW' },
  { name: 'Palestyna', code: 'PS' },
  { name: 'Panama', code: 'PA' },
  { name: 'Papua-Nowa Gwinea', code: 'PG' },
  { name: 'Paragwaj', code: 'PY' },
  { name: 'Peru', code: 'PE' },
  { name: 'Filipiny', code: 'PH' },
  { name: 'Polska', code: 'PL' },
  { name: 'Portugalia', code: 'PT' },
  { name: 'Katar', code: 'QA' },
  { name: 'Rumunia', code: 'RO' },
  { name: 'Rosja', code: 'RU' },
  { name: 'Rwanda', code: 'RW' },
  { name: 'Saint Kitts i Nevis', code: 'KN' },
  { name: 'Saint Lucia', code: 'LC' },
  { name: 'Saint Vincent i Grenadyny', code: 'VC' },
  { name: 'Samoa', code: 'WS' },
  { name: 'San Marino', code: 'SM' },
  { name: 'Wyspy Świętego Tomasza i Książęca', code: 'ST' },
  { name: 'Arabia Saudyjska', code: 'SA' },
  { name: 'Senegal', code: 'SN' },
  { name: 'Serbia', code: 'RS' },
  { name: 'Seszele', code: 'SC' },
  { name: 'Sierra Leone', code: 'SL' },
  { name: 'Singapur', code: 'SG' },
  { name: 'Słowacja', code: 'SK' },
  { name: 'Słowenia', code: 'SI' },
  { name: 'Wyspy Salomona', code: 'SB' },
  { name: 'Somalia', code: 'SO' },
  { name: 'Republika Południowej Afryki', code: 'ZA' },
  { name: 'Korea Południowa', code: 'KR' },
  { name: 'Sudan Południowy', code: 'SS' },
  { name: 'Hiszpania', code: 'ES' },
  { name: 'Sri Lanka', code: 'LK' },
  { name: 'Sudan', code: 'SD' },
  { name: 'Surinam', code: 'SR' },
  { name: 'Szwecja', code: 'SE' },
  { name: 'Szwajcaria', code: 'CH' },
  { name: 'Syria', code: 'SY' },
  { name: 'Tajwan', code: 'TW' },
  { name: 'Tadżykistan', code: 'TJ' },
  { name: 'Tanzania', code: 'TZ' },
  { name: 'Tajlandia', code: 'TH' },
  { name: 'Timor Wschodni', code: 'TL' },
  { name: 'Togo', code: 'TG' },
  { name: 'Tonga', code: 'TO' },
  { name: 'Trynidad i Tobago', code: 'TT' },
  { name: 'Tunezja', code: 'TN' },
  { name: 'Turcja', code: 'TR' },
  { name: 'Turkmenistan', code: 'TM' },
  { name: 'Tuvalu', code: 'TV' },
  { name: 'Uganda', code: 'UG' },
  { name: 'Ukraina', code: 'UA' },
  { name: 'Zjednoczone Emiraty Arabskie', code: 'AE' },
  { name: 'Wielka Brytania', code: 'GB' },
  { name: 'Stany Zjednoczone', code: 'US' },
  { name: 'Urugwaj', code: 'UY' },
  { name: 'Uzbekistan', code: 'UZ' },
  { name: 'Vanuatu', code: 'VU' },
  { name: 'Wenezuela', code: 'VE' },
  { name: 'Wietnam', code: 'VN' },
  { name: 'Jemen', code: 'YE' },
  { name: 'Zambia', code: 'ZM' },
  { name: 'Zimbabwe', code: 'ZW' }
];
